{% set name = "aiida-nwchem" %}
{% set version = "2.1.0" %}
{% set build = 3 %}
{% set name_code = name + ".code" %}

package:
  name: {{ name }}.meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida_nwchem-{{ version }}.tar.gz
  sha256: 33ecc7b012ad05b4f3a2bd8e7c11abfe4a15083f9c5fd00250f64b048d73897c

build:
  number: {{ build }}
  noarch: python

requirements:
  run:
  - {{ pin_subpackage(name, exact=True) }}
  - {{ pin_subpackage(name_code, exact=True) }}

outputs:

  - name:  {{ name }}
    build:
      noarch: python
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - pip
        - python >=3.7,<3.10
        - reentry
      run:
        - aiida-core.atomic_tools >=1.2.1,<2
        - numpy
        - python >=3.7
      run_constrained:
        - {{ name_code }} =={{ version }}
    test:
      imports:
        - aiida_nwchem
      commands:
        - pip check
      requires:
        - pip
  
  - name: {{ name_code }}
    build:
      noarch: python
    requirements:
      run:
        - nwchem =7
    test:
      commands:
        - which nwchem

about:
  home: https://github.com/aiidateam/aiida-nwchem
  summary: The official AiiDA plugin for NWChem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
